# Generated by Django 4.2.13 on 2024-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('critical_level', models.FloatField(verbose_name='Критическое значение')),
            ],
        ),
    ]
