# Generated by Django 4.2.13 on 2024-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPV5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('critical_level', models.FloatField(verbose_name='Критическое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'РПВ-5',
                'verbose_name_plural': 'РПВ-5',
            },
        ),
        migrations.CreateModel(
            name='RPV6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('critical_level', models.FloatField(verbose_name='Критическое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'РПВ-6',
                'verbose_name_plural': 'РПВ-6',
            },
        ),
        migrations.CreateModel(
            name='RPV7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('critical_level', models.FloatField(verbose_name='Критическое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'РПВ-7',
                'verbose_name_plural': 'РПВ-7',
            },
        ),
        migrations.DeleteModel(
            name='WaterLevel',
        ),
    ]
