# Generated by Django 4.2.13 on 2024-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0003_remove_rpv5_name_remove_rpv6_name_remove_rpv7_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpv5',
            name='consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='rpv5',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление'),
        ),
        migrations.AddField(
            model_name='rpv6',
            name='consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='rpv6',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление'),
        ),
        migrations.AddField(
            model_name='rpv7',
            name='consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='rpv7',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление'),
        ),
    ]
